1 IFFRE(0)<24400THENPRINT"PRESS <CTRL> UNTIL BEEP":DEFUSR=0:A=USR(0)
2 SCREEN0:WIDTH40:KEYOFF:PRINT"GAUNTLET":PRINT"--------":PRINT
3 PRINT"(C) 1985 ATARI GAMES":PRINT:PRINT"CONVERSION BY GREMLIN GRAPHICS":PRINT:PRINT"DISK VERSION BY MARTOS":PRINT
4 PRINT"2ND JOY BUTTON AND KEYBOARD VERSION BY"
5 PRINT"JOSE ANGEL MORENTE AND"
6 PRINT"ROBERTO VARGAS":PRINT:PRINT:PRINT"GAUNTLET IS LOADING ....."
9 BLOAD"gaunt.1",R
10 BLOAD"gaunt.2",R
11 BLOAD"gaunt.3",R
